language: minimal

sudo: required

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

env:
  - ARCH=amd64 HARDWARE=default PLATFORM=amd64
  - ARCH=arm32v7 HARDWARE=default PLATFORM=arm32/v7
  - ARCH=arm64v8 HARDWARE=default PLATFORM=arm64/v8
  - ARCH=arm32v7 HARDWARE=rpi PLATFORM=arm32/v7
  - ARCH=arm64v8 HARDWARE=rpi PLATFORM=arm64/v8

before_script:
  - "echo '{\"experimental\": true}' | sudo tee /etc/docker/daemon.json"
  - sudo service docker restart
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

script:
  - |
    set -e
    [[ "$TRAVIS_TAG" == "" ]] && VERSION=dev || VERSION=$TRAVIS_TAG
    [[ "$HARDWARE" == "default" ]] && REPO_SUFFIX="-${ARCH}" || REPO_SUFFIX="-${ARCH}-${HARDWARE}"

    docker pull robertme/cec2mqtt${REPO_SUFFIX}:cec || true

    docker build . --platform=linux/${PLATFORM} --build-arg PLATFORM="${HARDWARE}" -f docker/Dockerfile.${ARCH} --cache-from robertme/cec2mqtt${REPO_SUFFIX}:cec -t robertme/cec2mqtt${REPO_SUFFIX}:${VERSION}

    if [[ $TRAVIS_TAG != "" || $TRAVIS_BRANCH == "master" ]]; then
      docker push robertme/cec2mqtt${REPO_SUFFIX}:${VERSION}

      docker build . --target dev --platform=linux/${PLATFORM} --build-arg PLATFORM="${HARDWARE}" -f docker/Dockerfile.${ARCH} --cache-from robertme/cec2mqtt${REPO_SUFFIX}:cec -t robertme/cec2mqtt${REPO_SUFFIX}:cec
      docker push robertme/cec2mqtt${REPO_SUFFIX}:cec
    fi

jobs:
  include:
    - stage: deploy
      script: |
        set -e
        export DOCKER_CLI_EXPERIMENTAL=enabled
        [[ "$TRAVIS_TAG" == "" ]] && VERSION=dev || VERSION=$TRAVIS_TAG
        docker pull robertme/cec2mqtt-amd64:${VERSION}
        docker pull robertme/cec2mqtt-arm32v7:${VERSION}
        docker pull robertme/cec2mqtt-arm64v8:${VERSION}

        docker manifest create robertme/cec2mqtt:${VERSION} robertme/cec2mqtt-amd64:${VERSION} robertme/cec2mqtt-arm32v7:${VERSION} robertme/cec2mqtt-arm64v8:${VERSION}
        docker manifest annotate robertme/cec2mqtt:${VERSION} robertme/cec2mqtt-arm32v7:${VERSION} --os linux --arch arm --variant 7
        docker manifest annotate robertme/cec2mqtt:${VERSION} robertme/cec2mqtt-arm64v8:${VERSION} --os linux --arch arm64 --variant 8
        docker manifest inspect robertme/cec2mqtt:${VERSION}
        docker manifest push --purge robertme/cec2mqtt:${VERSION}

        docker pull robertme/cec2mqtt-arm32v7-rpi:${VERSION}
        docker pull robertme/cec2mqtt-arm64v8-rpi:${VERSION}

        docker manifest create robertme/cec2mqtt:rpi-${VERSION} robertme/cec2mqtt-arm32v7-rpi:${VERSION} robertme/cec2mqtt-arm64v8-rpi:${VERSION}
        docker manifest annotate robertme/cec2mqtt:rpi-${VERSION} robertme/cec2mqtt-arm32v7-rpi:${VERSION} --os linux --arch arm --variant 7
        docker manifest annotate robertme/cec2mqtt:rpi-${VERSION} robertme/cec2mqtt-arm64v8-rpi:${VERSION} --os linux --arch arm64 --variant 8
        docker manifest inspect robertme/cec2mqtt:rpi-${VERSION}
        docker manifest push --purge robertme/cec2mqtt:rpi-${VERSION}

        if [[ $TRAVIS_TAG != "" ]]; then
          docker tag robertme/cec2mqtt-amd64:${VERSION} robertme/cec2mqtt-amd64:latest
          docker tag robertme/cec2mqtt-arm32v7:${VERSION} robertme/cec2mqtt-arm32v7:latest
          docker tag robertme/cec2mqtt-arm64v8:${VERSION} robertme/cec2mqtt-arm64v8:latest

          docker manifest create robertme/cec2mqtt:latest robertme/cec2mqtt-amd64:latest robertme/cec2mqtt-arm32v7:latest robertme/cec2mqtt-arm64v8:latest
          docker manifest annotate robertme/cec2mqtt:latest robertme/cec2mqtt-arm32v7:latest --os linux --arch arm --variant 7
          docker manifest annotate robertme/cec2mqtt:latest robertme/cec2mqtt-arm64v8:latest --os linux --arch arm64 --variant 8
          docker manifest inspect robertme/cec2mqtt:latest
          docker manifest push --purge robertme/cec2mqtt:latest

          docker tag robertme/cec2mqtt-arm32v7-rpi:${VERSION} robertme/cec2mqtt-arm32v7-rpi:latest
          docker tag robertme/cec2mqtt-arm64v8-rpi:${VERSION} robertme/cec2mqtt-arm64v8-rpi:latest

          docker manifest create robertme/cec2mqtt:rpi robertme/cec2mqtt-arm32v7-rpi:latest robertme/cec2mqtt-arm64v8-rpi:latest
          docker manifest annotate robertme/cec2mqtt:rpi robertme/cec2mqtt-arm32v7-rpi:latest --os linux --arch arm --variant 7
          docker manifest annotate robertme/cec2mqtt:rpi robertme/cec2mqtt-arm64v8-rpi:latest --os linux --arch arm64 --variant 8
          docker manifest inspect robertme/cec2mqtt:rpi
          docker manifest push --purge robertme/cec2mqtt:rpi
        fi
        export DOCKER_CLI_EXPERIMENTAL=disabled
